version: '0.0.1'

services:
  api:
    build:
      context: ./api
      dockerfile: ../dockerfiles/api/Dockerfile.prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:5000
    volumes:
      - static_volume:/home/api/staticfiles
      - media_volume:/home/api/mediafiles
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    tty: true

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  spa:
    build:
      context: ./spa
      dockerfile: ../dockerfiles/spa/Dockerfile.prod
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./spa
        target: /usr/src/spa
    env_file:
      - ./.env.dev
    tty: true

  nginx:
    build: 
      context: ./nginx
      dockerfile: ../dockerfiles/nginx/Dockerfile.prod
    volumes:
      - static_volume:/home/api/app/staticfiles
      - media_volume:/home/api/app/mediafiles
    ports:
      - 1337:80
    depends_on:
      - api 
    tty: true


volumes:
  postgres_data:
  static_volume:
  media_volume:
  