version: '0.0.1'

services:
  api:
    build: ./api
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - ./api/:/usr/src/api/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=JnU4MJirGUoto8
      - POSTGRES_DB=recipes_dev
  
volumes:
  postgres_data: