version: '0.0.1'

services:
  api:
    build:
      context: ./api
      dockerfile: ../dockerfiles/api/Dockerfile
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - type: bind
        source: ./api
        target: /usr/src/api
      - static_volume:/usr/src/api/staticfiles
      - media_volume:/usr/src/api/mediafiles
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  spa:
    build:
      context: ./spa
      dockerfile: ../dockerfiles/spa/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./spa
        target: /usr/src/spa
    env_file:
      - ./.env.dev
    tty: true

  db:
    image: postgres:15-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
  
volumes:
  postgres_data:
  static_volume:
  media_volume:
