# Generated by Django 4.2.1 on 2023-06-05 09:06

import api.constants
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdc_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('base_quanqity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[(api.constants.RecipeStatus['DRAFT'], 'Draft'), (api.constants.RecipeStatus['AWAITING'], 'Awaiting'), (api.constants.RecipeStatus['NEEDED_CHANGES'], 'Needed Changes'), (api.constants.RecipeStatus['REJECTED'], 'Rejected'), (api.constants.RecipeStatus['PUBLISHED'], 'Published'), (api.constants.RecipeStatus['ARCHIVED'], 'Archived'), (api.constants.RecipeStatus['DELETED'], 'Deleted')], max_length=50)),
                ('cooking_time', models.DurationField()),
                ('nutritonal_values', models.JSONField(default=None, verbose_name='NutritionalValues')),
                ('difficulty', models.SmallIntegerField(choices=[(api.constants.DifficultyLv['NA'], api.constants.DifficultyLv['NA']), (api.constants.DifficultyLv['VERY_EASY'], api.constants.DifficultyLv['VERY_EASY']), (api.constants.DifficultyLv['EASY'], api.constants.DifficultyLv['EASY']), (api.constants.DifficultyLv['MODERATE'], api.constants.DifficultyLv['MODERATE']), (api.constants.DifficultyLv['HARD'], api.constants.DifficultyLv['HARD']), (api.constants.DifficultyLv['VERY_HARD'], api.constants.DifficultyLv['VERY_HARD'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cuisine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cuisine')),
                ('dish_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dishtype')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.SmallIntegerField(choices=[(api.constants.UnitType['MASS'], 0), (api.constants.UnitType['VOLUME'], 1)])),
                ('system', models.SmallIntegerField(choices=[(api.constants.UnitSystem['METRIC'], 0), (api.constants.UnitSystem['IMPERIAL'], 1), (api.constants.UnitSystem['US'], 2)])),
                ('base_value', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('Ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recipe')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.unit')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingreditents',
            field=models.ManyToManyField(through='api.RecipeIngredients', to='api.ingredient'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.unit'),
        ),
    ]
